#!/bin/bash

# Get the current working directory
current_dir=$(pwd)

# Change to the target directory
cd /home/borislav/Desktop/ferris/dev_tool/

# Execute the Python script
python3 main.py

# Change back to the previous working directory
cd "$current_dir"

